### ISSUE TITLE
Problem with Controlling Hand

### ISSUE THREAD

**Issue by adilmahsan** [erdalpekel/panda_simulation#1]
Hi,

First off, thank you for sharing these tutorials and these files... They are a big help... :)

I had a problem... I'm not sure how i'm supposed to control the robot hand... 

For example, when i try using the moveit commander command line interface, and try using either the groups 'hand' or 'panda_arm_hand', i always get the message Failed while moving to goal.

Using the group 'panda_arm' works correctly.

Thanks... :) 
![Screenshot from 2019-04-26 18-44-24](https://user-images.githubusercontent.com/27216313/56823204-7f5ebc00-6853-11e9-87dc-d88e65104707.png)
![Screenshot from 2019-04-26 19-26-57](https://user-images.githubusercontent.com/27216313/56825421-5b9e7480-6859-11e9-8508-3592fc13ff2a.png)

**Comment by erdalpekel** [comment]
Hi @adilmahsan 

I have a different version of the panda_moveit_config and franka_ros repositories where the gripper control works.
I will have to check the differences to the versions on GitHub in order to find out why it is not working.

**Comment by adilmahsan** [comment]
Thanks @erdalpekel ... :)

**Comment by erdalpekel** [comment]
Just fixed this issue by patching my [franka_ros](https://github.com/erdalpekel/franka_ros) fork.
Moving the gripper should now work.
