### ISSUE TITLE
Unable to simulate rviz-created plans in gazebo

### ISSUE THREAD

**Issue by SebastianEbert** [erdalpekel/panda_simulation#10]
Dear Erdal,

I followed the instructions in your readme & your blog, but unfortunately I am not able to simulate the plans created in rviz in the Gazebo-Environment. I hope you can give me a hint about what I can do to get it working.  You can see all information and my log below. Thanks in advance.

**My Environment:**
- ROS Melodic
- Ubuntu 18.04.4 LTS
- Current version of MoveIt

**What I already tried:**
- Run it with libfranka 0.6.0, 0.7.1, ros-melodic shipped libfranka
- integrated your changes on franka_ros into ros-melodic

**Log:**

<pre><font color="#FF4B4B">[ERROR] [1584633581.317447289, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_joint1</font>
<font color="#FF4B4B">[ERROR] [1584633581.318023500, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_joint2</font>
<font color="#FF4B4B">[ERROR] [1584633581.318550172, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_joint3</font>
<font color="#FF4B4B">[ERROR] [1584633581.318997989, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_joint4</font>
<font color="#FF4B4B">[ERROR] [1584633581.319560690, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_joint5</font>
<font color="#FF4B4B">[ERROR] [1584633581.320012283, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_joint6</font>
<font color="#FF4B4B">[ERROR] [1584633581.320441589, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_joint7</font>
<font color="#FF4B4B">[ERROR] [1584633581.320937503, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_finger_joint1</font>
<font color="#FF4B4B">[ERROR] [1584633581.321403157, 0.358000000]: No p gain specified for pid.  Namespace: /gazebo_ros_control/pid_gains/panda_finger_joint2</font>
[ INFO] [1584633581.324496048, 0.358000000]: Loaded gazebo_ros_control.
[INFO] [1584633581.333322, 0.359000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1584633581.334815, 0.359000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1584633581.336450, 0.359000]: Loading controller: panda_hand_controller
<font color="#FF4B4B">[ERROR] [1584633581.364777974, 0.366000000]: Could not find joint &apos;panda_finger_joint1&apos; in &apos;hardware_interface::EffortJointInterface&apos;.</font>
<font color="#FF4B4B">[ERROR] [1584633581.364973330, 0.366000000]: Failed to initialize the controller</font>
<font color="#FF4B4B">[ERROR] [1584633581.365025908, 0.366000000]: Initializing controller 

&apos;panda_hand_controller&apos; failed</font>
<font color="#F78C8C"><b>[Err] [REST.cc:205] Error in REST request</b></font>

libcurl: (51) SSL: no alternative certificate subject name matches target host name &apos;api.ignitionfuel.org&apos;
<b>[spawn_urdf-4] process has finished cleanly</b>
<b>log file: /home/sebastian/.ros/log/a259ca5c-69fa-11ea-8838-f875a49f9fe4/spawn_urdf-4*.log</b>
[INFO] [1584633581.605707, 0.606000]: Controller Spawner: Waiting for service controller_manager/switch_controller
[INFO] [1584633581.607730, 0.608000]: Controller Spawner: Waiting for service controller_manager/unload_controller
[INFO] [1584633581.609528, 0.609000]: Loading controller: joint_state_controller
[INFO] [1584633581.615283, 0.616000]: Loading controller: panda_arm_controller
<font color="#FF4B4B">[ERROR] [1584633581.620880308, 0.621000000]: Could not find joint &apos;panda_joint1&apos; in &apos;hardware_interface::EffortJointInterface&apos;.</font>
<font color="#FF4B4B">[ERROR] [1584633581.620941163, 0.621000000]: Failed to initialize the controller</font>
<font color="#FF4B4B">[ERROR] [1584633581.621004136, 0.621000000]: Initializing controller &apos;panda_arm_controller&apos; failed</font>
<font color="#FF4B4B">[ERROR] [1584633582.366421, 1.357000]: Failed to load panda_hand_controller</font>
</pre>

**Comment by erdalpekel** [comment]
Hi Sebastian,

please make sure that you clone the newest versions of franka_ros and panda_moveit_config repositories (from my profile, not the official versions from Franka Emika) into your workspace.

Because the newest versions do not use the EffortJointInterface; this comes up for panda_joint1 in your logs:

> Could not find joint 'panda_joint1' in 'hardware_interface::EffortJointInterface'.

Erdal

**Comment by SebastianEbert** [comment]
thx :)  thats what I already did. Do I need to explicitly say in the build-command that it has to use your repo as ROS-installation and not my via apt-get installed ros-melodic. If yes how? Also the panda looks a bit strange (https://imgur.com/9E1Tf7V).

i tried it now again but the first error in my log plus the below is still there:

<pre><font color="#FF4B4B">[ERROR] [1584637246.665694575, 29.857000000]: RRTConnect: Motion planning start tree could not be initialized!</font></pre>

**Comment by erdalpekel** [comment]
Ok. Please have a look at my last [blog post](https://erdalpekel.de/?p=285) where I describe how to solve that problem at the end. You need to switch the controller in order to command the robot to a valid state, then switch back and reset the MoveIt plugin.

> Custom Position Control – Fixing invalid Robot States in Gazebo.

I will soon push changes to the repository where the robot moves to a valid state automatically.

**Comment by erdalpekel** [comment]
And also select **panda_arm** as planning_group in the RViz window.

**Comment by SebastianEbert** [comment]
thank you Erdal, it works now fine :)
