### ISSUE TITLE
robot_control_node fails after startup

### ISSUE THREAD

**Issue by vincent-mayer** [erdalpekel/panda_simulation#23]
Hi Erdal,

unfortunately I can't make the robot to move after startup of RVIZ and Gazebo. The following errors are being printed to console: 

![image](https://user-images.githubusercontent.com/50368404/98984680-d2c25900-2522-11eb-8723-94b3f19d4b8c.png)
Afterwards this fails:
![image](https://user-images.githubusercontent.com/50368404/98984778-f2598180-2522-11eb-8869-a6a15ec28ec1.png)

A quick look in the log file reveals this:
1. spawn_urdf-4.log
![image](https://user-images.githubusercontent.com/50368404/98985147-6dbb3300-2523-11eb-9c1b-fba97237fa01.png)
2. master.log
![image](https://user-images.githubusercontent.com/50368404/98985215-87f51100-2523-11eb-93c6-1bb1502bb50f.png)

I built the newest version of libfranka from source. Does it require an older version of libfranka maybe?

**Comment by Islemlhr** [comment]
hey ,
can you tell me please how did you fixe it ?
