### ISSUE TITLE
Grippers not physical

### ISSUE THREAD

**Issue by rouzinho** [erdalpekel/panda_simulation#24]
Hi !

Very nice work there. I actually try to push a cube with the grippers but they are not colliding with it. The grippers go through like there was nothing there. I am sure that my cube model is okay since a different robot (iCub) manage to push it.

Best,

Quentin

**Comment by rouzinho** [comment]
Never mind I just discovered that the collision of the fingers were not implemented. I did it by adding the necessary sections from this franka panda description [https://github.com/justagist/franka_panda_description](url) (with the according values) 
In more details :
```
<link name="${ns}_leftfinger">
      <visual>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <geometry>
          <mesh filename="package://franka_description/meshes/collision/finger.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 0" xyz="0 0.0145644 0.0227941"/>
        <mass value="0.1"/>
        <inertia ixx="3.01220925051e-05" ixy="0.0" ixz="0.0" iyy="2.95873808038e-05" iyz="0.0" izz="6.95125211657e-06"/>
      </inertial>
      <!-- for simulation
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.68" />
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
      </inertial>
       end for simulation -->
    </link>
    <link name="${ns}_rightfinger">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://franka_description/meshes/visual/finger.dae"/>
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 ${pi}"/>
        <geometry>
          <mesh filename="package://franka_description/meshes/collision/finger.stl"/>
        </geometry>
      </collision>
      <inertial>
        <origin rpy="0 0 3.141592653589793" xyz="0 -0.0145644 0.0227941"/>
        <mass value="0.1"/>
        <inertia ixx="3.01220925051e-05" ixy="0.0" ixz="0.0" iyy="2.95873808038e-05" iyz="0.0" izz="6.95125211657e-06"/>
      </inertial>
      <!-- for simulation
      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <mass value="0.68" />
        <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1" />
      </inertial>
       end for simulation -->
   </link>
```

**Comment by JGioia** [comment]
@rouzinho This is somewhat unrelated, but have you been able to pick up the box with the fingers? I think we are working on very similar tasks, so I was wondering if you managed to get past the issue I was having. I am able to grip the box with the fingers, but when I try to pick it up, gazebo acts like there is no friction.

**Comment by rouzinho** [comment]
@JGioia I didn't try that since I only need to push objects around (similar to RL experiments with robotics arms in openAI gym). But I remember coming across a similar problem of yours on google when I was looking to solve my issue with the physical grippers.
