### ISSUE TITLE
Missing include

### ISSUE THREAD

**Issue by kingjin94** [erdalpekel/panda_simulation#4]
When following your blockposts and the README to install the panda simulator I stumbled across the following issue when launching the simulator: 

> [FATAL] [1561640151.166516932]: Exception while loading controller manager 'moveit_simple_controller_manager/MoveItSimpleControllerManager': According to the loaded plugin descriptions the class moveit_simple_controller_manager/MoveItSimpleControllerManager with base class type moveit_controller_manager::MoveItControllerManager does not exist. Declared types are  moveit_fake_controller_manager/MoveItFakeControllerManager

I fixed it by adding `<depend>moveit_simple_controller_manager</depend>` to the dependencies in package.xml.

**Comment by erdalpekel** [comment]
Hi @kingjin94 

I will add the dependency to the package.xml file

Thanks for reporting!
