### ISSUE TITLE
Error while making

### ISSUE THREAD

**Issue by rns0869** [erdalpekel/panda_simulation#45]
Hello @erdalpekel, I am trying to build the panda_simulation using the instruction in the read me.
I am using ubuntu 20.04.
So my build fails, the screenshot is below( also if you see top of screenshot it says Error2 and waiting for unfinished jobs)
![Error_1_build_fail](https://github.com/erdalpekel/panda_simulation/assets/79132373/05dfc893-1817-4c38-837c-27c2b17d9d09)

But when I build in the beginning I also get a cmake warning regarding OpenMesh as shown in the screenshot below:

![Warning_1](https://github.com/erdalpekel/panda_simulation/assets/79132373/373a19c3-3b1c-439e-9e15-9b4c0d0c5632)

I installed OpenMesh from source and  I followed the instructions here: https://www.graphics.rwth-aachen.de/media/openmesh_static/Documentations/OpenMesh-6.2-Documentation/a00030.html

Is the cmake warning related to the repository not building?
do you have any suggestions for me, how to build it?

**Comment by rohansingh080699** [comment]
I was able to solve the issue and build the panda_simulation workspace,  the cmake error was not related to the building fail.

**Comment by rns0869** [comment]
I was able to solve the issue and build the panda_simulation workspace, the cmake warning was not directly related to the building fail.
