### ISSUE TITLE
Self collision at start pose

### ISSUE THREAD

**Issue by Wurmi1010** [erdalpekel/panda_simulation#8]
Hello @erdalpekel,

first, thanks for your great work implementing FRANKA into Gazebo.

Regarding my problem:
I'm trying for a few days now to implement your model of FRANKA into gazebo and it works more or less. I followed your tutorial and also installed libfranka from source. Worked great so far. But then I run `roslaunch panda_simulation simulation.launch`.

It opens two windows: Rviz(upper picture) and Gazebo(lower picture).
![Screenshot_2020-03-10_rviz](https://user-images.githubusercontent.com/33329212/76350688-790eec80-630c-11ea-85a2-205f086ddf2b.png)
![Screenshot_2020-03-10_gazebo](https://user-images.githubusercontent.com/33329212/76350694-7ad8b000-630c-11ea-8b88-be6afaa1e486.png)

As you can see FRANKA is colliding with itself and so I can't do any planning nor executing the paths in Rviz.

Here is the full output from the launch command: [full_output_from_launch.txt](https://github.com/erdalpekel/panda_simulation/files/4314368/full_output_from_launch.txt)

I'm working with Ubuntu 18.04 and ROS Melodic.

Do you have an idea what the problem could be and how to solve it?

Best regards,
Christian

**Comment by erdalpekel** [comment]
Hi @Wurmi1010 

Please have a look at my [latest blog post](https://erdalpekel.de/?p=285) where I solve this problem at the end.

**Comment by Wurmi1010** [comment]
Thanks a lot! That solved it!

**Comment by Wurmi1010** [comment]
Hi @erdalpekel,

is there a way to automate the solution for this problem? Maybe just writing a shell script?

**Comment by erdalpekel** [comment]
Hi @Wurmi1010 

You can read my newest [blog post](https://erdalpekel.de/?p=314).
Pull the latest state and start the simulation. It should automatically reset itself.

Erdal

**Comment by Wurmi1010** [comment]
Oh I didn't see. Thanks a lot!
